#include "engine/loader/safetensors.h"

#include <stdexcept>

namespace engine {

/*
TODO(JOE): parse_safetensors_header

Purpose. This function reads the header of a .safetensors file that is already mapped into memory and returns, for every tensor in the file, its dtype, its shape and the exact byte range its data occupies. It exists so that exactly one place in the engine interprets the file format: the weight loader uses the result to validate the checkpoint against ModelConfig, plan the device layout and copy each tensor to the GPU, and nothing downstream looks at the length prefix or the JSON again. Because the file comes from disk, every byte of it is untrusted input.

Interface. The argument is the entire file as a read-only byte span, as returned by MappedFile::bytes(); the span outlives the call, and the result refers to the file only through offsets. The function returns a SafetensorsHeader. Its data_offset is the absolute file offset of the first byte after the JSON header, which is 8 plus the header length. Its tensors map holds one TensorEntry per tensor name, where dtype is the DType for the entry's dtype string, shape is the dimension list in file order (an empty list means a scalar with one element), offset is the absolute file offset of the tensor's first byte (data_offset plus the entry's begin offset), and bytes is the length of the tensor's data. On malformed input the function throws std::runtime_error with a message that says what is wrong and, when it concerns one tensor, names that tensor; no other exception type may escape. It never reads outside the span, never crashes on any input and never returns a partially valid result.

File format. The first 8 bytes are an unsigned 64-bit little-endian integer N, the length of the JSON header in bytes. The next N bytes are a UTF-8 JSON object, which may have whitespace before or after it inside those N bytes. Every key other than "__metadata__" is a tensor name whose value is an object with the fields "dtype" (a string), "shape" (an array of non-negative integers) and "data_offsets" (an array of exactly two non-negative integers [begin, end], relative to data_offset, with end exclusive); any other fields in that object are ignored. Integers must be written as JSON integers, so a number with a fraction or exponent, even 1.0, is an error. The optional "__metadata__" key is either null or an object whose values are all strings; it is not a tensor and does not appear in the result. Everything from data_offset to the end of the file is the data section.

Dtypes. The dtype strings "BF16", "F16", "F32", "I32" and "I64" map to the DType enumerators of the same names, and the comparison is case-sensitive, so "bf16" is an error. Every other dtype string is an error that names the tensor and the dtype, including strings the Python library accepts but the engine does not support, such as "F64", "I8", "U8", "BOOL" and "F8_E4M3".

Matching the reference. For every file the Python safetensors library (version pinned in scripts/requirements.txt) accepts and whose dtypes are all supported, the result must list the same tensor names, dtypes, shapes and byte ranges that library reports. Every file that library rejects must be rejected here too. That library requires the byte ranges of all tensors, ordered by begin, to tile the data section exactly: the first range begins at 0, each range begins where the previous one ends, the last ends at the end of the file, and no two overlap. It also requires each tensor's end minus begin to equal the product of its dimensions times the dtype size. The order of keys in the JSON does not matter, and when a key appears more than once the last occurrence is the one that counts.

Edge cases and boundaries. A file shorter than 8 bytes is an error. N larger than 100,000,000 is an error regardless of the file size, which is also the reference's limit. N larger than the number of bytes remaining after the 8-byte prefix is an error, and this check must give the right answer for every N up to 2^64 - 1. N equal to the remaining bytes is valid and means the data section is empty, in which case the object must contain no tensors with non-zero size. A header that is not valid UTF-8, is not valid JSON, or whose top level is not an object is an error. A tensor value that is not an object is an error, and so is a tensor entry that is missing a field, has a field of the wrong JSON type, has a negative or non-integer dimension or offset, has data_offsets with other than two elements, or has begin greater than end. A "__metadata__" that is neither null nor an object, or an object with a non-string value, is an error. Zero-sized tensors (any dimension 0, so begin equals end) are valid and take part in the tiling rule. The product of the dimensions times the dtype size must be computed so that a shape whose true byte size does not fit in 64 bits is rejected instead of wrapping around to a value that happens to match the range. Gaps between ranges, overlapping ranges, a range ending past the end of the file and bytes after the last range are all errors. Tensor names are compared as plain strings, so "model.layers.10.mlp.up_proj.weight" sorts before "model.layers.2.mlp.up_proj.weight" in the map.

What to compare against. For the real checkpoint, compare names, dtypes, shapes and absolute offsets with what the Python safetensors library reports for models/tinyllama/model.safetensors (201 tensors, all BF16). For malformed input, compare with the rules above, each of which was checked against that library's behavior.

Tests that prove it. tests/todo/unit/test_safetensors.cpp builds files byte by byte and has one test per rule above, plus RealTinyLlamaHeader for the actual checkpoint (skipped when the model is absent). These run in the todo_unit_tests target with the todo_joe label, so ctest --preset debug -L todo_joe shows them failing until this function is implemented. When they all pass, move the file to tests/unit/, add it to unit_tests and delete todo_unit_tests if it is empty. The checksum golden test in branch 7 then checks the parser and loader together against Python on all 201 tensors.
*/
SafetensorsHeader parse_safetensors_header(std::span<const std::byte>) {
    throw std::logic_error("unimplemented: parse_safetensors_header");
}

}  // namespace engine
