#include <cstdio>
#include <cstdlib>

#include "engine/kernels/paged_attention.h"

namespace engine {

/*
TODO(JOE): paged_attention_decode

Purpose. paged_attention_decode is the attention of one decode step over the paged KV cache: each row of the batch is one query token of one sequence, and it attends to every token of that sequence in the cache, itself included, by following the sequence's block table. It replaces naive::attention, which reads a single sequence from a contiguous cache. The model runner calls it once per layer, after write_kv has stored the step's keys and values, so the current token's K and V are read from the cache like those of every earlier token. Because each row carries its own block table and context length, the same kernel can also serve a prefill, one row per prompt token with context length pos + 1 and all rows of a prompt sharing one block table (the build plan's MVP prefill); whether the runner does that is decided in branch 20.

Interface. k_cache and v_cache are BF16 tensors of the same shape [num_blocks, kv_heads, block_size, head_dim], contiguous and row-major (the views KvCache::k(layer) and KvCache::v(layer) return): the K vector of kv head g for the token in slot s is k_cache[s / block_size][g][s % block_size][0 .. head_dim - 1], and likewise for V. out is BF16 [B, heads * head_dim], which fixes heads = out.shape[1] / head_dim. qkv is the BF16 [B, width] output of the fused QKV GEMM after RoPE, width = (heads + 2 * kv_heads) * head_dim; only its Q columns are read, and columns h * head_dim to h * head_dim + head_dim - 1 are the query q_h of head h (the K and V columns are never read). block_tables is I32 [B, max_blocks] and context_lens is I32 [B], both in device memory. stream is the stream to run on. For row b with L = context_lens[b] > 0, token j of the row's sequence (0 <= j < L) is in physical block block_tables[b][j / block_size] at offset j % block_size, and query head h reads kv head h / (heads / kv_heads) (grouped-query attention: in TinyLlama 8 query heads share each of the 4 kv heads). Then out[b][h * head_dim + d] = sum over j < L of p_j * V_j[d], where p is the softmax over j < L of the scores s_j = scale * (q_h . K_j) and scale = 1 / sqrt(head_dim). A row with L = 0 is padding: nothing of out row b is written. qkv, both caches, block_tables and context_lens are not modified.

Numerics. Each score is rounded the way HF's eager BF16 attention rounds it (a BF16 matmul, then a BF16 multiply by the scale): s_j = bf16(bf16(q_h . K_j) * scale), with the dot product accumulated in FP32 before the first rounding. On the traced reference prompt, scores kept in FP32 instead put up to 16 outputs of a layer outside the HF bound below (in 4 of the 22 layers), because real scores are large enough that one BF16 ulp of a score shows in the output. After the scores, the result may differ from naive::attention within the tolerance below: the probabilities may stay in FP32 or be rounded to BF16 as naive::attention rounds them, the sums may run in any order as long as they accumulate in FP32, and the output is rounded to BF16 once. The result must stay finite and correct when scores are large: the tests reach scores of 128, where exp overflows in FP32. A row's output depends only on its query, the first ceil(L / block_size) entries of its block table and the L cached tokens they reach: the slots past position L - 1 in its last block, every other block, and the table entries after the ones in use must not change a single bit of it, even when they hold NaN (a debug KvCache starts as 0xFF bytes, BF16 NaN) or huge values. The result is deterministic, and a row's output is bit-identical whether it is computed alone or in any batch; the M3 criterion that 16 concurrent requests produce the same text as 16 sequential runs relies on this.

Errors and preconditions. Before launching anything, throw std::invalid_argument with a message naming paged_attention_decode when: k_cache or v_cache is not BF16 or not 4-dimensional, or their shapes differ; out is not BF16 or not 2-dimensional, its width is not a multiple of head_dim, or heads is not a positive multiple of kv_heads; qkv is not BF16 or not 2-dimensional, its row count differs from out's, or its width is not (heads + 2 * kv_heads) * head_dim; block_tables is not I32 or not 2-dimensional, its row count is not B, or it has no columns; context_lens is not I32 or not 1-dimensional, or its length is not B. The caller guarantees, without checks (they would need a copy back to the host), that 0 <= context_lens[b] <= max_blocks * block_size and that the first ceil(context_lens[b] / block_size) entries of row b of block_tables are between 0 and num_blocks - 1; later entries may hold anything, including -1. Several rows may read the same blocks. The launch is asynchronous on stream, with the usual KERNEL_CHECK after it.

Edge cases and boundaries. B = 0 is a valid call that does nothing and must not launch a kernel with an empty grid. A context of one token gives exactly V_0 for every head, bit for bit. Contexts of block_size - 1, block_size and block_size + 1 tokens, and 2,048 tokens (the MVP context cap: a full 128-entry table of 16-token blocks) must all be right, and block 0 (the null block) is read like any other. It must be correct for any positive block_size, kv_heads and head_dim, any heads that is a multiple of kv_heads (the tests use head dims 4 to 128 and block sizes 1 to 32), and every context length up to 2,048. It may reject, with std::invalid_argument, a table whose capacity max_blocks * block_size exceeds 2,048 tokens, but must accept every width up to that.

What to compare against. naive::attention on a contiguous copy of the row's L cached tokens with start = L - 1, within 1/64 of (sum over j of p_j * |V_j[d]|) + |naive output| per element, where p is the exact softmax computed in double from the BF16 inputs; and HF's attn output of every layer on the traced reference prompt, within 2^-7 times the largest |V| of the visible tokens in that column, the bound naive::attention meets in tests/gpu/test_attention.cpp.

Tests that prove it. tests/todo/gpu/test_paged_attention.cpp: a 37-token sequence through a shuffled block table, context lengths 1, 2, 15, 16, 17, 31, 32 and 33 alone and as one batch, 2,048-token contexts with a full table, a 16-sequence decode batch with mixed lengths, padding rows (with guard elements around out proving nothing outside the real rows is written), scores up to 128, a one-token context equal to V bit for bit, NaN and huge values outside the contexts and -1 table entries leaving the output bit-identical, batch invariance and repeatability, rows sharing one table as a prefill, six odd head and block layouts, HF's attn on all 22 layers, B = 0, and every rejected argument. The caches are filled with random values first, so a read of a wrong slot shows. They run in the todo_gpu_tests target with the todo_joe label (ctest --preset debug -L todo_joe). When they all pass, move the file to tests/gpu/, add it to gpu_tests and delete todo_gpu_tests if it is empty; also run compute-sanitizer --tool memcheck on them.
*/
void paged_attention_decode(const Tensor&, const Tensor&, const Tensor&, const Tensor&,
                            const Tensor&, const Tensor&, Stream) {
    std::fprintf(stderr, "unimplemented: paged_attention_decode\n");
    std::abort();
}

}  // namespace engine
